@url = http://localhost:5000
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVhYjlkNmRkZTI4N2UyZjU3OTAxZTJhIn0sImlhdCI6MTU4ODMxMjMyNywiZXhwIjoxNTg4NjcyMzI3fQ.9TsQgilgCSZ6SEyI8Zs2iexY73KomYquxKQf_Xh8aiQ


### register user
POST {{url}}/api/users HTTP/1.1
Content-Type: {{contentType}}

{
    "n3ame": "Desh Bhatta",
    "email": "upadesh.ng@gmail.com",
    "password": "123456"
}

### register user
POST {{url}}/api/users HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "aak1",
    "email": "aak1.ng@gmail.com",
    "password": "123456"
}